# Generated by Django 5.1.4 on 2024-12-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=100)),
                ('group_description', models.CharField(default='helpfull', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('logo', models.ImageField(upload_to='')),
                ('motive_type', models.CharField(choices=[('Social cause', 'Social cause'), ('Environmental', 'Environmental'), ('educational', 'educational'), ('Medical', 'Medical'), ('Charity', 'Charity'), ('Other', 'Other')], default='Social cause', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
